---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# kpitools


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Tools for creating KPI reports.

CURRENTLY CREATES LATEX OUTPUT ONLY

Example usage 

```{r, eval = FALSE}
data(mtcars)

mtcars$highmpg <- mtcars$mpg > 25

kpis <- list()

ref <- "highmgp"

kpis[[ref]] <- kpi_fn(mtcars,
                      ref = ref, # used to create latex refs
                      vars = "highmpg", # variable in the dataframe
                      indicator = "High MPG", # text label used in figures, tables
                      previous = old_kpis[[ref]], # a previous object generated by kpi_fn
                      fn = kpi_fn_median, # function to summarize the KPI
                      measure = "MPG", # text used in table headers
                      firsttime = FALSE) # logical for whether it's the first time or not

```

This creates 2 figures (indicator value per country and per site) and 7 tables (overall study, outliers for countries and sites, country and site listings). The items are then printed via 

```{r, eval = FALSE}
kpi_print_elements(kpis[[ref]]) # for the main text (figures, overall and outliers)
kpi_print_elements(kpis[[ref]], appendix = TRUE) # for the listings
```





